
crafting.addShaped(item("techguns:t4_power_boots"),[
	[item("techguns:t3_power_boots"),ore("plateIridium"),ore("gearEnderium")],
	[ore("plateIridium"),ore("plateIridium"),item("techguns:itemshared:67")],
	[ore("gearEnderium"),item("techguns:itemshared:67"),item("techguns:itemshared:67")]
]);
crafting.addShaped(item("techguns:t4_power_leggings"),[
	[item("techguns:t3_power_leggings"),ore("plateIridium"),ore("gearEnderium")],
	[ore("plateIridium"),ore("plateIridium"),item("techguns:itemshared:67")],
	[ore("gearEnderium"),item("techguns:itemshared:67"),item("techguns:itemshared:67")]
]);
crafting.addShaped(item("techguns:t4_power_chestplate"),[
	[item("techguns:t3_power_chestplate"),ore("plateIridium"),ore("gearEnderium")],
	[ore("plateIridium"),ore("plateIridium"),item("techguns:itemshared:67")],
	[ore("gearEnderium"),item("techguns:itemshared:67"),item("techguns:itemshared:67")]
]);
crafting.addShaped(item("techguns:t4_power_helmet"),[
	[item("techguns:t3_power_helmet"),ore("plateIridium"),ore("gearEnderium")],
	[ore("plateIridium"),ore("plateIridium"),item("techguns:itemshared:67")],
	[ore("gearEnderium"),item("techguns:itemshared:67"),item("techguns:itemshared:67")]
]);

crafting.addShaped(item("techguns:t4_praetor_boots"),[
	[ore("ingotNetherite"),null,ore("ingotNetherite")],
	[ore("ingotNetherite"),null,ore("ingotNetherite")],
	[item("techguns:itemshared:67"),null,item("techguns:itemshared:67")]
]);
crafting.addShaped(item("techguns:t4_praetor_leggings"),[
	[item("techguns:itemshared:67"),ore("ingotNetherite"),item("techguns:itemshared:67")],
	[ore("ingotNetherite"),ore("ingotNetherite"),ore("ingotNetherite")],
	[item("techguns:itemshared:67"),null,item("techguns:itemshared:67")]
]);
crafting.addShaped(item("techguns:t4_praetor_chestplate"),[
	[ore("ingotNetherite"),item("techguns:itemshared:67"),ore("ingotNetherite")],
	[ore("ingotNetherite"),item("techguns:itemshared:131"),ore("ingotNetherite")],
	[item("techguns:itemshared:67"),item("techguns:itemshared:67"),item("techguns:itemshared:67")]
]);
crafting.addShaped(item("techguns:t4_praetor_helmet"),[
	[ore("netherStar"),ore("ingotNetherite"),ore("netherStar")],
	[ore("ingotNetherite"),item("techguns:itemshared:67"),ore("ingotNetherite")],
	[item("techguns:itemshared:67"),ore("blockGlassHardened"),item("techguns:itemshared:67")]
]);

crafting.addShaped(item("techguns:jumppack"),[
	[ore("nuggetSteel"),ore("nuggetSteel"),item("thermalfoundation:material:352")],
	[item("techguns:itemshared:352"),item("thermalfoundation:material:90"),item("thermalfoundation:material:352")],
	[item("techguns:itemshared:23"),null,item("techguns:itemshared:23")]
]);
crafting.addShaped(item("techguns:jetpack"),[
	[item("techguns:itemshared:27"),null,item("techguns:itemshared:27")],
	[item("techguns:itemshared:67"),item("techguns:jumppack"),item("techguns:itemshared:67")],
	[item("techguns:itemshared:145"),ore("gearIridium"),item("techguns:itemshared:145")]
]);
